### ISSUE TITLE
Camera option not working properly

### ISSUE THREAD

**Issue by sanchitgarg1909** [awkward/Tatsi#19]
I have set the showCameraOption as true in the config. The camera option is there, but when I click a photo through, it does not get saved anywhere. Neither it is returned in the didPickAssets function. Is it a bug? Or am I missing something in the code?

**Comment by renssies** [comment]
@sanchitgarg1909 First of all, sorry for the slow reply. I was out of the office because of the holidays. 

I have diagnosed the issue and it looks like we were using an old API that no longer works when Tatsi is compiled with the iOS 12.X SDK. That should be fixed now in the master and on Cocoapods! Be sure to update to release 1.1.4
